config/routes.rb
RealizeTheatre::Application.routes.draw do
  
  resources :posts, :users, :events
  

  get '/about' => 'public_pages#about', :as => :about
  get '/contact' => 'public_pages#contact', :as => :contact
  get '/shows' => 'public_pages#shows', :as => :shows
  get '/donate' => 'public_pages#donate', :as => :donate
  
  get '/login' => 'sessions#new', :as => :login
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => :logout
  
  root :to => 'public_pages#posts'
  

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  
  belongs_to :post
  belongs_to :event
  belongs_to :user
  
  image_accessor :image
end

app/models/email_list.rb
class EmailList < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  #SEO
  extend FriendlyId
  friendly_id :title, :use => :slugged
  #
  
  has_many :attachments, :dependent => :destroy
  
  accepts_nested_attributes_for :attachments
  attr_accessible :attachments_attributes, :title, :about, :location, :date, :publish, :slug
  
  validates :title, presence: true
  validates :about, presence: true
  validates :location, presence: true
  validates :date, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  #SEO
  extend FriendlyId
  friendly_id :title, :use => :slugged
  #
  
  has_many :attachments, :dependent => :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :attachments
  attr_accessible :attachments_attributes, :title, :body, :publish, :user_id, :slug
  
  validates :title, presence: true
  validates :body, presence: true

end

app/models/thumb.rb
class Thumb < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :name, :email, :bio, :password, :password_confirmation, :admin
  has_secure_password
  
  has_many :posts
  has_many :attachments
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper
  before_filter :login_user! # , except: [:index, :show]

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :login_user!, only: [:show]
  
  def index
    @events = Event.find(:all, :order => "created_at DESC")
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.new(params[:event])
    if @event.save
      flash[:success] = "Created Successfully!"
      redirect_to events_url
    else
      render 'new'
    end
    
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:success] = "Updated Successfully!"
      redirect_to events_url
    else
      render 'edit'
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = "Deleted"
      redirect_to events_url
    else
      render 'edit'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :login_user!, only: [:show]
  
  def index
    @posts = Post.find(:all, :conditions => ["id != ?", 1], :order => "created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:success] = "Created Successfully!"
      redirect_to posts_url
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:success] = "Updated Successfully!"
      redirect_to posts_url
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.destroy
      flash[:success] = "Deleted"
      redirect_to posts_url
    else
      render 'edit'
    end
  end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController
  skip_before_filter :login_user!
  
  def about
    @about = Post.find(1)
    @users = User.find(:all, :order => "random()")
  end
  
  def posts
    # The first post with id of 1 is my hack for the text on the about page above the users, didn't want to add another model just for that
    @posts = Post.find(:all, :conditions => ["id != ? and publish = ?", 1, true], :order => "created_at DESC")
  end
  
  def shows
    @events = Event.find(:all, :conditions => ["publish = ?", true], :order => "created_at DESC")
  end
  
  def contact
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :login_user!, only: [:new, :create]
  
  def new
     
  end
  
  def create
    user = User.find_by_email(params[:email])
         if user.present?
           if user.authenticate(params[:password])
             session[:user] = user.id
             redirect_to root_url
           else
             flash.now[:error] = 'Invalid email/password combo..'
             render 'new'
           end
         else
           flash.now[:error] = 'Invalid email/password combo..'
           render 'new'
           # redirect_to login_url, notice: "Incorrect login. Please try again"
         end
  end
  
  def destroy
    reset_session
    redirect_to :root
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_user!, only: [:show]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
      @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Created Successfully!"
      redirect_to users_url
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Updated Successfully!"
      redirect_to users_url
    else
      render 'edit'
    end
  end
  
  def destroy
    if current_user? || admin?
      @user = User.find_by_id(params[:id])
      @user.destroy
    end
    redirect_to users_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # include TweetButton
  
  def icon(name, content)
    raw("<i class=\"icon-#{name}\"></i> ") + content
  end
  
  def is_active?(path)
    "active" if current_page?(path)
  end
  
  def is_current?(path)
    current_page?(path)  
  end
  
  def content_tag_for(url, title, id)
    content_tag(:li, link_to( is_current?(url) ? icon("share-alt", title) : title, url, class: is_active?(url), id: id))
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end
  
  def current_user?
    current_user.present?
  end
  
  def current_name
    current_user.name.split(' ')[0]
  end
  
  def login_user!
    if current_user.nil?
      redirect_to login_url, notice: "You gotta sign in!"
    end
  end
  
  def admin?
    current_user.admin == true
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  
  def gravatar_for(user, options = { size: 50 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
    
end

app/views/events/_error_messages.html.haml
- if @event.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains
      = pluralize(@event.errors.count, "error")
    %ul
      - @event.errors.full_messages.each do |msg|
        %li= msg

app/views/events/_form.html.haml
.row
  = simple_nested_form_for(@event, :html => { :multipart => true, :class => 'form-vertical' }) do |f|
    = render 'error_messages', object: f.object
    .span4
      = f.input :title, :input_html => { :class => "span4" }
      = f.input :location, :input_html => { :class => "span4" }
      = f.input :date, :input_html => { :class => "span4" }
      = f.input :about, :input_html => { :class => "span4" }
      = f.input :publish, :as => :boolean
    .span3.well
      = f.fields_for :attachments do |attach|
        = attach.file_field :image, :class => "btn btn-warning"
        = attach.hidden_field :user_id, :value => current_user.id
        = attach.link_to_remove "Remove", :class => "btn btn-warning"
      = f.link_to_add "Add an Image", :attachments, :class => "btn btn-success"
    .form-actions.span8
      = f.button :submit, :class => 'btn-primary'
      = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"

app/views/events/edit.html.haml
.row
  .span8.offset2
    %h1 Edit Event
    = render 'form'

app/views/events/index.html.haml
.row
  .span8.offset2
    %h1 All Events
    = link_to icon("pencil", "New Event"), new_event_url, class: "btn btn-success"
    %table.table.table-striped
      %thead
        %tr
          %th Title
          %th Location
          %th Published?
          %th Edit
          %th Delete
      %tbody
        - @events.each do |e|
          %tr
            %td= e.title
            %td= e.location
            %td= e.publish ? "Yes" : "No"
            %td= link_to icon("edit", "Edit"), edit_event_url(e.id)
            %td= link_to icon("trash", "Delete Post"), event_url(e.id), method: :delete, confirm: "Are you sure you\'d like to delete this event?", disable_with: "Deleting...", class: "btn btn-danger"

app/views/events/new.html.haml
.row
  .span8.offset2
    %h1 New Event
    = render 'form'

app/views/events/show.html.haml
.row
  .span8.offset1.content
      .posts
        .page-header
          %h1.small= @event.title
        %p When?
        %h3= @event.date
        %p Where?
        %h3= @event.location
        %p= @event.about
        - if @event.attachments.count == 1
          - @event.attachments.each do |a|
            .post-image
              = image_tag(a.image.thumb('160x160#').url)
  = render 'shared/side_links'

app/views/layouts/_admin_menu.html.haml
.btn-group
  %a.btn.btn-info{:href => "#"}
    = icon("cogs", "Admin")
  %a.btn.btn-info.dropdown-toggle{"data-toggle" => "dropdown", :href => "#admin-menu"}
    %span.caret
  %ul.dropdown-menu
    = content_tag(:li, link_to(icon("user", "New User"), new_user_url))
    = content_tag(:li, link_to(icon("warning-sign", "Edit/Delete Users"), users_url))
    = content_tag(:li, link_to(icon("edit", "Edit About Page"), edit_post_url(1)))
    

app/views/layouts/_user_menu.html.haml
.btn-group
  %a.btn{:href => edit_user_url(current_user)}
    = icon("user", "#{current_name}")
  %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    %span.caret
  %ul.dropdown-menu
    = content_tag(:li, link_to(icon("file", "Posts"), posts_url))
    = content_tag(:li, link_to(icon("flag", "Events"), events_url))
    = content_tag(:li, link_to(icon("user", "My Profile"), edit_user_url(current_user)))
    %li.divider
    = content_tag(:li, link_to(icon("signout", "Logout, #{current_name}?"), logout_url))
    

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Realize Theatre Group"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    / %link(href="images/favicon.ico" rel="shortcut icon")
    / %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    / %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    / %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .bg-stripe#yellow= image_tag('y-stripe.png')
    .bg-stripe#blue= image_tag('b-stripe.png')
    .bg-stripe#green= image_tag('g-stripe.png')

    .container          
      .nav.pull-right.user-btns.well
        - if current_user?
          = render 'layouts/user_menu'
        - else
          %li= link_to "Login", login_url
        
        = render 'layouts/admin_menu' if current_user? && admin?
            
    .container
      .row
        .span12
          #head-nav.span1.offset7
            %ul.nav
              = content_tag_for(root_url, "Home", "y-link")
              = content_tag_for(shows_url, "Events", "b-link")
              = content_tag_for(about_url, "About Us", "g-link")
          #head-bg.span5.offset2
            / = image_tag('head-bg.png')
            %h1#realize realize
            %h2#theatre theatre group
    .container
      .row
        .span12
          - flash.each do |key, value|
            = content_tag(:div, value, class: "alert alert-#{key}")
          = yield
      .row
        %footer.span12
          %p &copy; Realize Theatre Group 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    
    :javascript
      $('.dropdown-toggle').dropdown()
    

app/views/posts/_error_messages.html.haml
- if @post.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains
      = pluralize(@post.errors.count, "error")
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg
      

app/views/posts/_form.html.haml
.row
  = simple_nested_form_for(@post, :html => { :multipart => true, :class => 'form-vertical' }) do |f|
    = render 'error_messages', object: f.object
    .span4
      = f.input :title, :input_html => { :class => "span4" }
      = f.input :body, :input_html => { :class => "span4" }
      = f.input :publish, :as => :boolean
      = f.hidden_field :user_id, :value => current_user.id
    .span3.well
      = f.fields_for :attachments do |attach|
        = attach.file_field :image, :class => "btn btn-warning"
        = attach.hidden_field :user_id, :value => current_user.id
        = attach.link_to_remove "Remove", :class => "btn btn-warning"
      = f.link_to_add "Add an Image", :attachments, :class => "btn btn-success"
    .form-actions.span8
      = f.button :submit, :class => 'btn-primary'
      = submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"

app/views/posts/edit.html.haml
.row
  .span8.offset2
    %h1 Edit Post
    = render 'form'

app/views/posts/index.html.haml
.row
  .span8.offset2
    %h1 All Posts
    = link_to icon("pencil", "New Post"), new_post_url, class: "btn btn-success"
    %table.table.table-striped
      %thead
        %tr
          %th Title
          %th Body
          %th Published?
          %th Edit
          %th Delete
      %tbody
        - @posts.each do |p|
          %tr
            %td= p.title
            %td= p.body
            %td= p.publish ? "Yes" : "No"
            %td= link_to icon("edit", "Edit"), edit_post_url(p.id)
            %td= link_to icon("trash", "Delete Post"), post_url(p.id), method: :delete, confirm: "Are you sure you\'d like to delete this post?", disable_with: "Deleting...", class: "btn btn-danger"

app/views/posts/new.html.haml
.row
  .span8.offset2
    %h1 New Post
    = render 'form'

app/views/posts/show.html.haml
.row
  .span8.offset1.content
    .posts
      %h2= @post.title
      %p= @post.body
      - if @post.attachments.count == 1
        - @post.attachments.each do |a|
          .post-image
            = image_tag(a.image.thumb('160x160#').url)
      %ul.post-info.unstyled
        %li<
          Written By:
          = link_to @post.user.name, user_url(@post.user.id)
        %li= "Posted " + distance_of_time_in_words_to_now(@post.created_at) + " ago.." 
  = render 'shared/side_links'

app/views/public_pages/about.html.haml
.row
  .span5.content
    .posts
      .page-header
        %h1= @about.title
      %p= @about.body
  .span5.content
    .posts
      .post-image
        = image_tag(@about.attachments.first.image.thumb('400x400').url) if @about.attachments.present?
  = render 'shared/side_links'
.row
  .span10.offset1.content
    .posts
      - @users.each do |u|
        .bios.span4
          %ul.grav.span4.unstyled
            %li= gravatar_for(u, size: "80")
            %li
              %h3= u.name
          .bio.span4
            %p= u.bio
          .contact.span4
            %p= icon("envelope", u.email)

app/views/public_pages/events.html.haml
.row
  .span8.offset1.content
    - @events.each do |p|
      .posts
        .page-header
          %h1.small= p.title
        %p When?
        %h3= p.date
        %p Where?
        %h3= p.location
        %p= raw(truncate(p.about, :length => 1000, :omission => '... (continued)'))
        - if p.attachments.count == 1
          - p.attachments.each do |a|
            .post-image
              = image_tag(a.image.thumb('160x160#').url)
  = render 'shared/side_links'

app/views/public_pages/posts.html.haml
.row
  .span8.offset1.content
    - @posts.each do |p|
      .posts
        %h2= p.title
        %p= raw(truncate(p.body, :length => 1000, :omission => '... (continued)'))
        - if p.attachments.count == 1
          - p.attachments.each do |a|
            .post-image
              = image_tag(a.image.thumb('160x160#').url)
        %ul.post-info.unstyled
          %li<
            Written By:
            = link_to p.user.name, user_url(p.user.id)
          %li= "Posted " + distance_of_time_in_words_to_now(p.created_at) + " ago.." 
          %li= link_to "Read More", post_url(p.id)
  = render 'shared/side_links'  

app/views/public_pages/shows.html.haml
.row
  .span8.offset1.content
    - @events.each do |p|
      .posts
        .page-header
          %h1.small= p.title
        %p When?
        %h3= p.date
        %p Where?
        %h3= p.location
        %p= raw(truncate(p.about, :length => 1000, :omission => '... (continued)'))
        - if p.attachments.count == 1
          - p.attachments.each do |a|
            .post-image
              = image_tag(a.image.thumb('160x160#').url)
  = render 'shared/side_links'

app/views/shared/_side_links.html.haml
.span2.content
  .posts#side-links
    %h4 Follow us!
    = link_to "Twitter"
    = link_to "Facebook"
    = link_to(icon("gift", "Donate"), donate_url, class: "btn btn-warning")
    %h4 Contact us
    = link_to "Contact"

app/views/users/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains
      = pluralize(@user.errors.count, "error")
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/users/_form.html.haml
.row
  = simple_form_for(@user, :html => { :multipart => true, :class => 'form-vertical' }) do |f|
    .span4
      = f.input :name, :input_html => { :class => "span4" }
      = f.input :email, :input_html => { :class => "span4" }
      = f.input :bio, :input_html => { :class => "span4" }
      = f.input :password, :input_html => { :class => "span4" }
      = f.input :password_confirmation, :input_html => { :class => "span4" }
      = f.input :admin, :as => :boolean, :input_html => { :class => "span4" } if admin?
      .control-group.optional.span4
        %label.control-label Avatar
        .controls
          = gravatar_for(@user)
        .controls
          = link_to "Change this", "http://en.gravatar.com/", target: "_blank"
    .form-actions.span12
      = f.button :submit, :class => 'btn-primary'

app/views/users/_new_form.html.haml
.row
  = simple_form_for(@user, :html => { :multipart => true, :class => 'form-vertical' }) do |f|
    .span6.offset2
      = f.input :name, :input_html => { :class => "span5" }
      = f.input :email, :input_html => { :class => "span5" }
      = f.input :password, :input_html => { :class => "span5" }
      = f.input :password_confirmation, :input_html => { :class => "span5" }
      = f.input :admin
    .form-actions.span8
      = f.button :submit, :class => 'btn-primary'

app/views/users/edit.html.haml
.row
  .span8.offset2
    %h2= @user.name.split(' ')[0] + "'s Profile"
    = render 'form'

app/views/users/index.html.haml
%h1 Everyone
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Email
      %th Admin?
      %th Edit
      %th Delete
  %tbody
    - @users.each do |u|
      %tr
        %td= u.name
        %td= u.email
        %td= u.admin ? "Yes" : "No"

        %td= link_to icon("edit", "Edit"), edit_user_url(u.id)
        %td= link_to icon("trash", "Delete User"), user_url(u.id), method: :delete, confirm: "Are you sure you\'d like to delete this user?", disable_with: "Deleting...", class: "btn btn-danger" 

app/views/users/new.html.haml
.row
  .span8.offset2
    %h1 New User
    - if admin?
      = render 'new_form'
    - else
      = redirect_to @root_url, notice: "Sorry, admins only"

app/views/users/show.html.haml
.row
  .span6.offset2.content
    .posts
      .bios.span4
        %ul.grav.span4.unstyled
          %li= gravatar_for(@user, size: "80")
          %li
            %h3= @user.name
        .bio.span4
          %p= @user.bio
        .contact.span4
          %p= icon("envelope", @user.email)
  = render 'shared/side_links'